/**
 * This is a demo file of how we can create our own api client,
 * We can use various libraries like OpenAPI for schema definition and generation 
 * Then the new types and routes are generated by a simple script, and we can use the generated types and routes to create our own api client.
 * For now I am declaring all the types and routes manually.
 */

import {
  ApiEndpoints,
  EndpointRequest,
  EndpointResponse,
  EndpointParams,
  ExtractMethod,
  ExtractPath,
  ApiResponse, ApiClientConfig
} from '@repo/api-types';

export class ApiError extends Error {
  constructor(
    public status: number,
    public statusText: string,
    public data?: unknown
  ) {
    super(`API Error: ${status} ${statusText}`);
    this.name = 'ApiError';
  }
}

export class TypeSafeApiClient {
  private config: Required<ApiClientConfig>;

  constructor(config: ApiClientConfig) {
    this.config = {
      timeout: 10000,
      headers: { 'Content-Type': 'application/json' },
      ...config,
    };
  }

  private async request<T extends keyof ApiEndpoints>(
    endpoint: T,
    params?: EndpointParams<T>,
    body?: EndpointRequest<T>
  ): Promise<ApiResponse<EndpointResponse<T>>> {
    const method = this.extractMethod(endpoint);
    const pathTemplate = this.extractPath(endpoint);
    const url = this.buildUrl(pathTemplate, params);

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), this.config.timeout);

    try {
      const response = await fetch(url, {
        method,
        headers: this.config.headers,
        body: body ? JSON.stringify(body) : undefined,
        signal: controller.signal,
      });

      clearTimeout(timeoutId);

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new ApiError(response.status, response.statusText, errorData);
      }

      // Handle 204 No Content responses
      if (response.status === 204) {
        return {
          data: undefined as unknown as EndpointResponse<T>,
          status: response.status,
          statusText: response.statusText,
        };
      }

      const data = await response.json();
      
      return {
        data,
        status: response.status,
        statusText: response.statusText,
      };
    } catch (error) {
      clearTimeout(timeoutId);
      
      if (error instanceof ApiError) {
        throw error;
      }
      
      if (error instanceof Error && error.name === 'AbortError') {
        throw new ApiError(408, 'Request Timeout');
      }
      
      throw new ApiError(0, 'Network Error', error);
    }
  }

  private extractMethod<T extends keyof ApiEndpoints>(endpoint: T): ExtractMethod<T> {
    return endpoint.split(' ')[0] as ExtractMethod<T>;
  }

  private extractPath<T extends keyof ApiEndpoints>(endpoint: T): ExtractPath<T> {
    return endpoint.split(' ')[1] as ExtractPath<T>;
  }

  private buildUrl<T extends keyof ApiEndpoints>(
    pathTemplate: string,
    params?: EndpointParams<T>
  ): string {
    let path = pathTemplate;
    
    if (params) {
      Object.entries(params as Record<string, string>).forEach(([key, value]) => {
        path = path.replace(`:${key}`, encodeURIComponent(value));
      });
    }
    
    return `${this.config.baseUrl}${path}`;
  }

  // Type-safe API methods
  async get<T extends keyof ApiEndpoints & `GET ${string}`>(
    endpoint: T,
    params?: EndpointParams<T>
  ): Promise<EndpointResponse<T>> {
    const response = await this.request(endpoint, params);
    return response.data;
  }

  async post<T extends keyof ApiEndpoints & `POST ${string}`>(
    endpoint: T,
    body: EndpointRequest<T>,
    params?: EndpointParams<T>
  ): Promise<EndpointResponse<T>> {
    const response = await this.request(endpoint, params, body);
    return response.data;
  }

  async put<T extends keyof ApiEndpoints & `PUT ${string}`>(
    endpoint: T,
    body: EndpointRequest<T>,
    params?: EndpointParams<T>
  ): Promise<EndpointResponse<T>> {
    const response = await this.request(endpoint, params, body);
    return response.data;
  }

  async delete<T extends keyof ApiEndpoints & `DELETE ${string}`>(
    endpoint: T,
    params?: EndpointParams<T>
  ): Promise<void> {
    await this.request(endpoint, params);
  }
}

// Create a singleton instance for the app
export const apiClient = new TypeSafeApiClient({
  baseUrl: process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001',
});

// Convenience methods for widgets
export const widgetApi = {
  getAll: () => apiClient.get('GET /widgets'),
  
  getById: (id: string) => apiClient.get('GET /widgets/:id', { id }),
  
  create: (data: EndpointRequest<'POST /widgets'>) => 
    apiClient.post('POST /widgets', data),
  
  update: (id: string, data: EndpointRequest<'PUT /widgets/:id'>) => 
    apiClient.put('PUT /widgets/:id', data, { id }),
  
  delete: (id: string) => apiClient.delete('DELETE /widgets/:id', { id }),
};